### ISSUE TITLE
General calendar issue.

### ISSUE THREAD

**Issue by yeasin1989** [weDevsOfficial/wp-project-manager#377]
Hi,

We have found that the normal subscriber/non-assigned user can see other user's tasks/milestones on the general calendar.
I have made a video clip here https://drive.google.com/file/d/1Y303Cy_cbi7OSGpG9QEDCAp2x-byvxFl/view?usp=drivesdk

Please check and fix the issue.

Thank you :)

**Comment by asaquzzaman** [comment]
@yeasin1989 

Fixed the issue. Wait for next release.

**Comment by yeasin1989** [comment]
@asaquzzaman,

Brother, I have checked the latest version and see this issue not fixed yet.
Please let me know the update.

Thank you :)
