### ISSUE TITLE
Some strings to be translated are not included in the wedevs-project-manager.php file

### ISSUE THREAD

**Issue by DAnn2012** [weDevsOfficial/wp-project-manager#475]
Some strings to be translated are not included in the **wedevs-project-manager.php**  file.

These are the strings and where they are placed in the source code:

**__( 'Transactional email triggered fatal error for callback ', 'wedevs-project-manager' ),**

https://github.com/weDevsOfficial/wp-project-manager/blob/43a16a8e8b66218ac5584a4835c3d976b2fdd2de/core/Notifications/Background_Emailer.php#L48
https://github.com/weDevsOfficial/wp-project-manager/blob/43a16a8e8b66218ac5584a4835c3d976b2fdd2de/core/Notifications/Notification.php#L112

<hr>

And this strings in `/wedevs-project-manager/vendor/appsero/client/src/Insights.php`:

**__( 'Want to help make <strong>%1$s</strong> even more awesome? Allow %1$s to collect non-sensitive diagnostic data and usage information.', 'wedevs-project-manager' ),**

`           $notice = sprintf( $this->client->__trans( 'Want to help make <strong>%1$s</strong> even more awesome? Allow %1$s to collect non-sensitive diagnostic data and usage information.' ), $this->client->name );`

**__( 'what we collect', 'wedevs-project-manager' ),**

`        $notice .= ' (<a class="' . $this->client->slug . '-insights-data-we-collect" href="#">' . $this->client->__trans( 'what we collect' ) . '</a>)';`

**__( 'Allow', 'wedevs-project-manager' ),**

`            echo ' <a href="' . esc_url( $optin_url ) . '" class="button-primary button-large">' . $this->client->__trans( 'Allow' ) . '</a>';`

**__( 'No thanks', 'wedevs-project-manager' ),**

`            echo ' <a href="' . esc_url( $optout_url ) . '" class="button-secondary button-large">' . $this->client->__trans( 'No thanks' ) . '</a>';`

...and all other strings that are in the source code of this file in "**__trans**", "**_etrans**" or directly as **text**.

<hr>

Thanks.

<hr>

**_Update - The following strings were added to the wedevs-project-manager.php file with version 2.6.4:_**

**__( 'Create a folder', 'wedevs-project-manager' ),
__( 'Upload a file', 'wedevs-project-manager' ),
__( 'Create a doc', 'wedevs-project-manager' ),
__( 'Link to Docs', 'wedevs-project-manager' ),**

https://github.com/weDevsOfficial/wp-project-manager/blob/873df9210fab832874b330c2bf657cbec48005e6/views/assets/src/components/project-files/pro-files.vue#L25-L35

<hr>

**_Update - The following strings were added to the wedevs-project-manager.php file with version 2.6.6:_**

**__( ' Comments', 'wedevs-project-manager' ),
__( ' Files', 'wedevs-project-manager' ),
__( ' Task Lists', 'wedevs-project-manager' ),
__( ' Tasks', 'wedevs-project-manager' ),
__( ' Discussions', 'wedevs-project-manager' ),
__( ' Milestones', 'wedevs-project-manager' ),**

https://github.com/weDevsOfficial/wp-project-manager/blob/43a16a8e8b66218ac5584a4835c3d976b2fdd2de/views/assets/src/components/project-lists/project-summary.vue#L119
https://github.com/weDevsOfficial/wp-project-manager/blob/43a16a8e8b66218ac5584a4835c3d976b2fdd2de/views/assets/src/components/project-lists/project-summary.vue#L103
https://github.com/weDevsOfficial/wp-project-manager/blob/43a16a8e8b66218ac5584a4835c3d976b2fdd2de/views/assets/src/components/project-lists/project-summary.vue#L93
https://github.com/weDevsOfficial/wp-project-manager/blob/43a16a8e8b66218ac5584a4835c3d976b2fdd2de/views/assets/src/components/project-lists/project-summary.vue#L73
https://github.com/weDevsOfficial/wp-project-manager/blob/43a16a8e8b66218ac5584a4835c3d976b2fdd2de/views/assets/src/components/project-lists/project-summary.vue#L83
https://github.com/weDevsOfficial/wp-project-manager/blob/43a16a8e8b66218ac5584a4835c3d976b2fdd2de/views/assets/src/components/project-lists/project-summary.vue#L113

<hr>

**Comment by DAnn2012** [comment]
Hi @mrabbani 

please could you kindly take a look at this my Issue report?

Thank you.

**Comment by arifulhoque7** [comment]
The i18n pipeline was reworked in the new UI revamp — translatable strings are now extracted through @wordpress/i18n and `pnpm makepot`. Closing as resolved by the UI revamp.

**Comment by DAnn2012** [comment]
Hello.

The problem is still present in **version 4.0.5**

Thanks.
